dev: &dev
  image: dispersed-backup_dev
  volumes:
    - ./:/go/src/github.com/ammesonb/dispersed-backup
  environment:
    - BUILDKITE_AGENT_ACCESS_TOKEN
    - BUILDKITE_JOB_ID
    - BUILDKITE_BUILD_ID
    - BUILDKITE_BUILD_NUMBER
    - GOPATH=/go/
  working_dir: /go/src/github.com/ammesonb/dispersed-backup



lint: &lint
  <<: *dev
  command: ["scripts/entry.sh", "lint"]

lint-ci:
  image: dispersed-backup_dev
  <<: *lint
  # Volumes cannot be added to using inheritance, so explicitly set them here
  volumes:
    - ./:/go/src/github.com/ammesonb/dispersed-backup
    - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent
  command: "ls"

test: &test
  <<: *dev
  command: ["scripts/entry.sh", "test"]

test-ci:
  image: dispersed-backup_dev
  <<: *test
  # Volumes cannot be added to using inheritance, so explicitly set them here
  volumes:
    - ./:/go/src/github.com/ammesonb/dispersed-backup
    - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent

build: &build
  <<: *dev
  command: ["go", "build"]
