ci: &ci
  build: .
  volumes:
    - ./:/go/src/github.com/ammesonb/dispersed-backup
    - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent
  environment:
    - BUILDKITE_AGENT_ACCESS_TOKEN
    - BUILDKITE_JOB_ID
    - BUILDKITE_BUILD_ID
    - BUILDKITE_BUILD_NUMBER
    - GOROOT=/usr/src/go/
    - GOPATH=/go

lint:
  <<: *ci
  command: "scripts/test.sh lint"

test:
  <<: *ci
  command: "scripts/test.sh test"

build:
  <<: *ci
  command: "go build"
