dev: &dev
  image: dispersed-backup_dev
  volumes:
    - "./:/go/src/github.com/ammesonb/dispersed-backup"
  environment:
    - GOPATH=/go/
  working_dir: /go/src/github.com/ammesonb/dispersed-backup


ci: &ci
  image: dispersed-backup_dev
  # This will overwrite the dev volumes, so include both
  volumes:
    - "./:/go/src/github.com/ammesonb/dispersed-backup"
    - "/usr/bin/buildkite-agent:/usr/bin/buildkite-agent"
  environment:
    - BUILDKITE_AGENT_ACCESS_TOKEN
    - BUILDKITE_JOB_ID
    - BUILDKITE_BUILD_ID
    - BUILDKITE_BUILD_NUMBER
    - GOPATH=/go/
  working_dir: /go/src/github.com/ammesonb/dispersed-backup


lint: &lint
  <<: *dev
  command: ["sh", "-c", "'./scripts/entry.sh lint'"]

lint-ci:
  image: dispersed-backup_dev
  image: dispersed-backup_dev
  # This will overwrite the dev volumes, so include both
  volumes:
    - "./:/go/src/github.com/ammesonb/dispersed-backup"
    - "/usr/bin/buildkite-agent:/usr/bin/buildkite-agent"
  environment:
    - BUILDKITE_AGENT_ACCESS_TOKEN
    - BUILDKITE_JOB_ID
    - BUILDKITE_BUILD_ID
    - BUILDKITE_BUILD_NUMBER
    - GOPATH=/go/
  working_dir: /go/src/github.com/ammesonb/dispersed-backup

test: &test
  <<: *dev
  command: ["sh", "-c", "'./scripts/entry.sh test'"]

test-ci:
  image: dispersed-backup_dev
  <<: *test
  <<: *ci

build: &build
  <<: *dev
  command: ["go", "build"]
