dev: &dev
  image: dispersed-backup_dev
  volumes:
    - ./:/go/src/github.com/ammesonb/dispersed-backup
  environment:
    - BUILDKITE_AGENT_ACCESS_TOKEN
    - BUILDKITE_JOB_ID
    - BUILDKITE_BUILD_ID
    - BUILDKITE_BUILD_NUMBER
    - GOPATH=/go/
  working_dir: /go/src/github.com/ammesonb/dispersed-backup

ci: &ci
  <<: *dev
  volumes:
    - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent


lint: &lint
  <<: *dev
  command: ["scripts/entry.sh", "lint"]

lint-ci:
  <<: *lint
  <<: *ci
  # Seems like volumes aren't inherited?
  volumes:
    - ./:/go/src/github.com/ammesonb/dispersed-backup

test: &test
  <<: *dev
  command: ["scripts/entry.sh", "test"]

test-ci:
  <<: *test
  <<: *ci
  # Seems like volumes aren't inherited?
  volumes:
    - ./:/go/src/github.com/ammesonb/dispersed-backup

build: &build
  <<: *dev
  command: ["go", "build"]

build-ci:
  <<: *ci
  <<: *build
