dev: &dev
  build: .
  volumes:
    - ./:/go/src/github.com/ammesonb/dispersed-backup
  environment:
    - BUILDKITE_AGENT_ACCESS_TOKEN
    - BUILDKITE_JOB_ID
    - BUILDKITE_BUILD_ID
    - BUILDKITE_BUILD_NUMBER
    - GOPATH=/go/
    - PROJECT_DIR=/go/src/github.com/ammesonb/dispersed-backup
  working_dir: /go/src/github.com/ammesonb/dispersed-backup

ci: &ci
  <<: *dev
  volumes:
    - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent


lint:
  <<: *dev
  command: "scripts/test.sh lint"

lint-ci:
  <<: *dev
  <<: *ci
  command: "$PROJECT_DIR/test.sh lint"

test:
  <<: *dev
  command: "scripts/test.sh test"

test-ci:
  <<: *dev
  <<: *ci
  command: "$PROJECT_DIR/test.sh test"

build:
  <<: *dev
  command: "go build"

build-ci:
  <<: *dev
  <<: *ci
  command: "go build"
