agents:
  queue: default

steps:
  - name: ":docker: build"
    command: "docker build -t dispersed-backup_dev ."

  - wait

  - name: "File check"
    command: "ls"

  - name: ":golangci-lint:"
    plugins:
      - docker-compose#v3.0.3:
          run: lint-ci

  - name: ":go: :test_tube:"
    plugins:
      - docker-compose#v3.0.3:
          run: test-ci
