agents:
  queue: default

steps:
  - name: ":docker: Build Image"
    command: "docker build -t dispersed-backup_dev ."

  - wait

  - name: ":go: Imports"
    plugins:
      - docker-compose#v3.0.3:
          run: imports

  - name: ":go: :do_not_litter: Format"
    plugins:
      - docker-compose#v3.0.3:
          run: imports

  - name: ":go: :lab_coat: Vet"
    plugins:
      - docker-compose#v3.0.3:
          run: vet

  - name: ":golangci-lint: GoLangCI"
    plugins:
      - docker-compose#v3.0.3:
          run: ci-lint

  - name: ":go: :judge: Critic"
    plugins:
      - docker-compose#v3.0.3:
          run: critic

  - name: ":go: :bicyclist: Cycles"
    plugins:
      - docker-compose#v3.0.3:
          run: cycles

  - wait

  - name: ":go: :test_tube: Unit Tests"
    plugins:
      - docker-compose#v3.0.3:
          run: test-ci
