agents:
  queue: default

steps:
  - name: ":docker: build"
    command: "docker build -t dispersed-backup_dev ."

  - wait

  - name: ":golangci-lint: Linting"
    plugins:
      - docker-compose#v3.0.3:
          run: lint-ci
          volumes:
            - "${BUILDKITE_BUILD_PATH}/${HOSTNAME}-1/ammesonb/dispersed-backup:/go/src/github.com/ammesonb/dispersed-backup"
            - "/usr/bin/buildkite-agent:/usr/bin/buildkite-agent"

  - name: ":go: :test_tube: Unit Tests"
    plugins:
      - docker-compose#v3.0.3:
          run: test-ci
          volumes:
            - "${BUILDKITE_BUILD_PATH}/${HOSTNAME}-1/ammesonb/dispersed-backup:/go/src/github.com/ammesonb/dispersed-backup"
            - "/usr/bin/buildkite-agent:/usr/bin/buildkite-agent"
